services:
  server-db-init:
    image: zabbix/zabbix-server-pgsql:ubuntu-7.4-latest
    hostname: zabbix-server-pgsql-init
    container_name: zabbix-server-pgsql-init
    depends_on:
      postgres-server:
        condition: service_started
    init: true
    attach: true
    volumes:
      - ./zbx_env/var/lib/zabbix/dbscripts:/var/lib/zabbix/dbscripts:ro
#     - ./zbx_env/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
#     - ./zbx_env/.ZBX_DB_CERT_FILE:/run/secrets/client-cert.pem:ro
#     - ./zbx_env/.ZBX_DB_KEY_FILE:/run/secrets/client-key.pem:ro
#     - pgsql_socket:/var/run/postgresql
    command: init_db_only
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    environment:
      - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB=zabbix
#      - DB_SERVER_HOST=postgres-server
#      - DB_SERVER_PORT=5432
#      - POSTGRES_USER=zabbix
#      - POSTGRES_PASSWORD=zabbix
#      - POSTGRES_DB=zabbix
#      - DB_SERVER_SCHEMA=public
#      - ENABLE_TIMESCALEDB=true
#      - POSTGRES_USE_IMPLICIT_SEARCH_PATH=false

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-7.4-latest
    hostname: zabbix-server
    container_name: zabbix-server
    depends_on:
      server-db-init:
        condition: service_completed_successfully
    environment:
      - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB=zabbix
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
      - ZBX_STARTJAVAPOLLERS=5
      - ZBX_ENABLE_SNMP_TRAPS=true
#      - DB_SERVER_HOST=postgres-server
#      - DB_SERVER_PORT=5432
#      - POSTGRES_USER=zabbix
#      - POSTGRES_PASSWORD=zabbix
#      - POSTGRES_DB=zabbix
#      - DB_SERVER_SCHEMA=public
#      - ENABLE_TIMESCALEDB=true
#      - POSTGRES_USE_IMPLICIT_SEARCH_PATH=false
#      - ZBX_LISTENIP=
#      - ZBX_LISTENPORT=10051
#      - ZBX_LISTENBACKLOG=
#      - ZBX_HISTORYSTORAGEURL=http://elasticsearch:9200/ # Available since 3.4.5
#      - ZBX_HISTORYSTORAGETYPES=uint,dbl,str,log,text # Available since 3.4.5
#      - ZBX_ALLOWUNSUPPORTEDDBVERSIONS=0 # Available since 6.0.0
#      - ZBX_MAXCONCURRENTCHECKSPERPOLLER=1000 # Available since 7.0.0
#      - ZBX_DBTLSCONNECT=required # Available since 5.0.0
#      - ZBX_DBTLSCAFILE=/run/secrets/root-ca.pem # Available since 5.0.0
#      - ZBX_DBTLSCERTFILE=/run/secrets/client-cert.pem # Available since 5.0.0
#      - ZBX_DBTLSKEYFILE=/run/secrets/client-key.pem # Available since 5.0.0
#      - ZBX_DBTLSCIPHER= # Available since 5.0.0
#      - ZBX_DBTLSCIPHER13= # Available since 5.0.0
#      - ZBX_AUTOHANODENAME=fqdn # Allowed values: fqdn, hostname. Available since 6.0.0
#      - ZBX_HANODENAME= # Available since 6.0.0
#      - ZBX_AUTONODEADDRESS=fqdn # Allowed values: fqdn, hostname. Available since 6.0.0
      - ZBX_NODEADDRESSPORT=10051 # Allowed to use with ZBX_AUTONODEADDRESS variable only. Available since 6.0.0
      - ZBX_NODEADDRESS=zabbix-server:10051 # Available since 6.0.0
#      - ZBX_DEBUGLEVEL=3
#      - ZBX_ENABLEGLOBALSCRIPTS=0 # Available since 7.0.0
#      - ZBX_STARTAGENTPOLLERS=1 # Available since 7.0.0
#      - ZBX_STARTPOLLERS=5
#      - ZBX_STARTIPMIPOLLERS=0
#      - ZBX_STARTPREPROCESSORS=3 # Available since 3.4.0
#      - ZBX_STARTCONNECTORS=0 # Available since 6.4.0
#      - ZBX_STARTPOLLERSUNREACHABLE=1
#      - ZBX_STARTTRAPPERS=5
#      - ZBX_STARTPINGERS=1
#      - ZBX_STARTDISCOVERERS=5
#      - ZBX_STARTODBCPOLLERS=1 # Available since 6.0.0
#      - ZBX_STARTHTTPAGENTPOLLERS=1 # Available since 7.0.0
#      - ZBX_STARTHTTPPOLLERS=1
#      - ZBX_STARTSNMPPOLLERS=1 # Available since 7.0.0
#      - ZBX_STARTHISTORYPOLLERS=5 # Available since 5.4.0
#      - ZBX_STARTTIMERS=1
#      - ZBX_STARTESCALATORS=1
#      - ZBX_STARTALERTERS=3 # Available since 3.4.0
#      - ZBX_STARTLLDPROCESSORS=2
#      - ZBX_JAVAGATEWAYPORT=10052
#      - ZBX_STARTVMWARECOLLECTORS=0
#      - ZBX_VMWAREFREQUENCY=60
#      - ZBX_VMWAREPERFFREQUENCY=60
#      - ZBX_VMWARECACHESIZE=8M
#      - ZBX_VMWARETIMEOUT=10
#      - ZBX_SOURCEIP=
#      - ZBX_SMSDEVICES=
#      - ZBX_HOUSEKEEPINGFREQUENCY=1
#      - ZBX_MAXHOUSEKEEPERDELETE=5000
#      - ZBX_PROBLEMHOUSEKEEPINGFREQUENCY=60
#      - ZBX_CACHESIZE=8M
#      - ZBX_CACHEUPDATEFREQUENCY=10
#      - ZBX_STARTDBSYNCERS=4
#      - ZBX_HISTORYCACHESIZE=16M
#      - ZBX_HISTORYINDEXCACHESIZE=4M
#      - ZBX_HISTORYSTORAGEDATEINDEX=0
#      - ZBX_TRENDCACHESIZE=4M
#      - ZBX_TRENDFUNCTIONCACHESIZE=4M
#      - ZBX_VALUECACHESIZE=8M
#      - ZBX_TIMEOUT=4
#      - ZBX_TRAPPERTIMEOUT=300
#      - ZBX_UNREACHABLEPERIOD=45
#      - ZBX_UNAVAILABLEDELAY=60
#      - ZBX_UNREACHABLEDELAY=15
#      - ZBX_LOGSLOWQUERIES=3000
#      - ZBX_EXPORTFILESIZE=
#      - ZBX_STARTPROXYPOLLERS=1
#      - ZBX_PROXYCONFIGFREQUENCY=10
#      - ZBX_PROXYDATAFREQUENCY=1
#      - ZBX_LOADMODULE="dummy1.so,dummy2.so,dummy10.so"
#      - ZBX_TLSCAFILE=
#      - ZBX_TLSCA=
#      - ZBX_TLSCRLFILE=
#      - ZBX_TLSCRL=
#      - ZBX_TLSCERTFILE=
#      - ZBX_TLSCERT=
#      - ZBX_TLSKEYFILE=
#      - ZBX_TLSKEY=
#      - ZBX_VAULT=HashiCorp # Available since 6.2.0
#      - ZBX_VAULTDBPATH=
#      - ZBX_VAULTTLSCERTFILE= # Available since 6.2.0
#      - ZBX_VAULTTLSKEYFILE= # Available since 6.2.0
#      - ZBX_VAULTURL=https://127.0.0.1:8200
#      - ZBX_VAULTPREFIX= # Available since 7.0.0
#      - VAULT_TOKEN=
#      - ZBX_STARTREPORTWRITERS=0
#      - ZBX_WEBSERVICEURL=http://zabbix-web-service:10053/report
#      - ZBX_SERVICEMANAGERSYNCFREQUENCY=60
#      - ZBX_ALLOWSOFTWAREUPDATECHECK=1 # Available since 7.0.0
#      - ZBX_WEBDRIVERURL=http://selenium:4444 # Available since 7.0.0
#      - ZBX_STARTBROWSERPOLLERS=1 # Available since 7.0.0
#      - DB_SERVER_HOST=postgres-server
#      - DB_SERVER_PORT=5432
#      - POSTGRES_USER=zabbix
#      - POSTGRES_PASSWORD=zabbix
#      - POSTGRES_DB=zabbix
#      - DB_SERVER_SCHEMA=public
#      - ENABLE_TIMESCALEDB=true
#      - POSTGRES_USE_IMPLICIT_SEARCH_PATH=false
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    init: true
    ports:
      - "161:161"
#      - "10050:10050"
    restart: unless-stopped
    attach: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
      - ./zbx_env/var/lib/zabbix/ssl/certs:/var/lib/zabbix/ssl/certs:ro
      - ./zbx_env/var/lib/zabbix/ssl/keys:/var/lib/zabbix/ssl/keys:ro
      - ./zbx_env/var/lib/zabbix/ssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca:rw
      - ./snmptraps:/var/lib/zabbix/snmptraps:roz
    tmpfs: /tmp
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    stop_grace_period: 30s
#  devices:
#   - "/dev/ttyUSB0:/dev/ttyUSB0"
#  cap_add:
#    - "NET_RAW"
    sysctls:
      - net.ipv4.ip_local_port_range=1024 64999
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
#      - net.ipv4.ping_group_range=0 1995

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-7.4-latest
    hostname: zabbix-web-nginx-pgsql
    container_name: zabbix-web-nginx-pgsql
    depends_on:
      server-db-init:
        condition: service_completed_successfully
    environment:
      - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB=zabbix
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_NAME=Composed installation
#      - DB_SERVER_HOST=postgres-server
#      - DB_SERVER_PORT=5432
#      - POSTGRES_USER=zabbix
#      - POSTGRES_PASSWORD=zabbix
#      - POSTGRES_DB=zabbix
#      - DB_SERVER_SCHEMA=public
#      - ENABLE_TIMESCALEDB=true
#      - POSTGRES_USE_IMPLICIT_SEARCH_PATH=false
#      - ZBX_SERVER_PORT=10051
#      - ZBX_DB_ENCRYPTION=true # Available since 5.0.0
#      - ZBX_DB_KEY_FILE=/run/secrets/client-key.pem # Available since 5.0.0
#      - ZBX_DB_CERT_FILE=/run/secrets/client-cert.pem # Available since 5.0.0
#      - ZBX_DB_CA_FILE=/run/secrets/root-ca.pem # Available since 5.0.0
#      - ZBX_DB_VERIFY_HOST=false # Available since 5.0.0
#      - ZBX_DB_CIPHER_LIST= # Available since 5.0.0
#      - ZBX_VAULT= # Available since 6.2.0
#      - ZBX_VAULTDBPATH=
#      - ZBX_VAULTURL=https://127.0.0.1:8200
#      - VAULT_TOKEN=
#      - ZBX_VAULTCERTFILE= # Available since 6.2.0
#      - ZBX_VAULTKEYFILE= # Available since 6.2.0
#      - ZBX_VAULTCACHE=false # Available since 6.2.0
#      - ZBX_HISTORYSTORAGEURL=http://elasticsearch:9200/ # Available since 3.4.5
#      - ZBX_HISTORYSTORAGETYPES=['uint', 'dbl', 'str', 'text', 'log'] # Available since 3.4.5
#      - ZBX_SSO_SETTINGS={} # Available since 5.0.0. Then will be converted from JSON to PHP array.
#      - ZBX_ALLOW_HTTP_AUTH=true # Available since 7.0.0
#      - ENABLE_WEB_ACCESS_LOG=true
#      - ZBX_MAXEXECUTIONTIME=600
#      - ZBX_MEMORYLIMIT=128M
#      - ZBX_POSTMAXSIZE=16M
#      - ZBX_UPLOADMAXFILESIZE=2M
#      - ZBX_MAXINPUTTIME=300
#      - ZBX_SESSION_NAME=zbx_sessionid
#      - Timezone one of: http://php.net/manual/en/timezones.php
#      - PHP_TZ=Europe/Riga
#      - ZBX_DENY_GUI_ACCESS=false
#      - ZBX_GUI_ACCESS_IP_RANGE=['127.0.0.1']
#      - ZBX_GUI_WARNING_MSG=Zabbix is under maintenance.
#      - HTTP_INDEX_FILE=index.php
#      - EXPOSE_WEB_SERVER_INFO=on
#      - PHP_FPM_PM=dynamic
#      - PHP_FPM_PM_MAX_CHILDREN=50
#      - PHP_FPM_PM_START_SERVERS=5
#      - PHP_FPM_PM_MIN_SPARE_SERVERS=5
#      - PHP_FPM_PM_MAX_SPARE_SERVERS=35
#      - PHP_FPM_PM_MAX_REQUESTS=0
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "80:8080"
      - "43:8443"
    restart: unless-stopped
    attach: false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
      - ./zbx_env/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
    tmpfs:
      - /tmp
      - /var/lib/php/session:mode=770,uid=1997,gid=1995
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 1m30s
      timeout: 3s
      retries: 3
      start_period: 40s
      start_interval: 5s
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535

  zabbix-agent:
    image: zabbix/zabbix-agent:ubuntu-7.4-latest
    hostname: zabbix-agent
    container_name: zabbix-agent
    init: true
    ports:
      - "10050:10050"
    restart: unless-stopped
    attach: false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
      - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
      - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - ./zbx_env/var/lib/zabbix/user_scripts:/var/lib/zabbix/user_scripts:ro
    tmpfs: /tmp
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
      mode: global
    environment:
      - ZBX_HOSTNAME=agente
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_PASSIVE_ALLOW=true
      - ZBX_PASSIVESERVERS=zabbix-server
      - ZBX_ACTIVE_ALLOW=true
#      - ZBX_ACTIVESERVERS=zabbix-server
#    - ZBX_SOURCEIP=
#    - ZBX_DEBUGLEVEL=3
#    - ZBX_ENABLEREMOTECOMMANDS=0 # Deprecated since 5.0.0
#    - ZBX_LOGREMOTECOMMANDS=0
#    - ZBX_FORCEACTIVECHECKSONSTART=0 # Available since 6.0.2
#    - ZBX_HEARTBEAT_FREQUENCY=60 # Available since 6.2
#    - ZBX_HOSTINTERFACE= # Available since 4.4.0
#    - ZBX_HOSTINTERFACEITEM= # Available since 4.4.0
#    - ZBX_LISTENIP=
#    - ZBX_LISTENPORT=10050
#    - ZBX_LISTENBACKLOG=
#    - ZBX_STARTAGENTS=10
#    - ZBX_HOSTNAMEITEM=system.hostname
#    - ZBX_METADATA=
#    - ZBX_METADATAITEM=
#    - ZBX_REFRESHACTIVECHECKS=5
#    - ZBX_BUFFERSEND=5
#    - ZBX_BUFFERSIZE=100
#    - ZBX_MAXLINESPERSECOND=20
#    - ZBX_ALIAS=""
#    - ZBX_TIMEOUT=3
#    - ZBX_UNSAFEUSERPARAMETERS=0
#    - ZBX_LOADMODULE="dummy1.so,dummy2.so,dummy10.so"
#    - ZBX_TLSCONNECT=unencrypted
#    - ZBX_TLSACCEPT=unencrypted
#    - ZBX_TLSCAFILE=
#    - ZBX_TLSCA=
#    - ZBX_TLSCRLFILE=
#    - ZBX_TLSCRL=
#    - ZBX_TLSSERVERCERTISSUER=
#    - ZBX_TLSSERVERCERTSUBJECT=
#    - ZBX_TLSCERTFILE=
#    - ZBX_TLSCERT=
#    - ZBX_TLSKEYFILE=
#    - ZBX_TLSKEY=
#    - ZBX_TLSPSKIDENTITY=
#    - ZBX_TLSPSKFILE=
#    - ZBX_TLSPSK=
#    - ZBX_DENYKEY=system.run[*]
#    - ZBX_ALLOWKEY=
    privileged: true
    pid: "host"
    stop_grace_period: 5s
    links:
      - zabbix-server

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:ubuntu-7.4-latest
    hostname: zabbix-snmptraps
    container_name: zabbix-snmptraps
    ports:
      - "162:1162"
    restart: unless-stopped
    attach: false
    read_only: true
    volumes:
      - ./snmptraps:/var/lib/zabbix/snmptraps:rwz
      - ./zbx_env/var/lib/zabbix/snmptrapd_config:/var/lib/zabbix/snmptrapd_config:rw
    tmpfs: /tmp
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    environment:
      - ZBX_SNMP_TRAP_DATE_FORMAT=+%Y-%m-%dT%T%z
      - ZBX_SNMP_TRAP_FORMAT=\n
      - ZBX_SNMP_TRAP_USE_DNS=false
    stop_grace_period: 5s

  zabbix-web-service:
    image: zabbix/zabbix-web-service:ubuntu-7.4-latest
    hostname: zabbix-web-service
    container_name: zabbix-web-service
    ports:
      - "10053:10053"
    restart: unless-stopped
    attach: false
    read_only: true
    volumes:
      - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
    tmpfs: /tmp
    security_opt:
      - seccomp:./env_vars/chrome_dp.json
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    environment:
      - ZBX_ALLOWEDIP=zabbix-server
#      - ZBX_DEBUGLEVEL=3
#      - ZBX_LISTENPORT=10053
#      - ZBX_LISTENIP=
#      - ZBX_TIMEOUT=3
#      - ZBX_TLSACCEPT=unencrypted
#      - ZBX_TLSCAFILE=
#      - ZBX_TLSCA=
#      - ZBX_TLSCERTFILE=
#      - ZBX_TLSCERT=
#      - ZBX_TLSKEYFILE=
#      - ZBX_TLSKEY=
#      - ZBX_IGNOREURLCERTERRORS=0
    stop_grace_period: 5s

  postgres-server:
    image: postgres:16-alpine
#    command: -c ssl=on -c ssl_cert_file=/run/secrets/server-cert.pem -c ssl_key_file=/run/secrets/server-key.pem -c ssl_ca_file=/run/secrets/root-ca.pem
    hostname: postgres-server
    container_name: postgres-server
    restart: unless-stopped
    attach: false
    volumes:
      - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw
      - ./env_vars/.ZBX_DB_CA_FILE:/run/secrets/root-ca.pem:ro
      - ./env_vars/.ZBX_DB_CERT_FILE:/run/secrets/server-cert.pem:ro
      - ./env_vars/.ZBX_DB_KEY_FILE:/run/secrets/server-key.pem:ro
#      - pgsql_socket:/var/run/postgresql/
    environment:
      - POSTGRES_USER_FILE=/run/secrets/POSTGRES_USER
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD
      - POSTGRES_DB=zabbix
#      - DB_SERVER_HOST=postgres-server
#      - DB_SERVER_PORT=5432
#      - POSTGRES_USER=zabbix
#      - POSTGRES_PASSWORD=zabbix
#      - POSTGRES_DB=zabbix
#      - DB_SERVER_SCHEMA=public
#      - ENABLE_TIMESCALEDB=true
#      - POSTGRES_USE_IMPLICIT_SEARCH_PATH=false
    secrets:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    stop_grace_period: 1m

  db-data-pgsql:
    image: busybox:latest
    attach: false
    volumes:
      - ./zbx_env/var/lib/postgresql/data:/var/lib/postgresql/data:rw

#  elasticsearch:
#    image: elasticsearch:9.0.1
#    restart: unless-stopped
#    attach: false
#    environment:
#      - transport.host=0.0.0.0
#      - discovery.zen.minimum_master_nodes=1
#      - MALLOC_ARENA_MAX=4
#      - refresh_rate=300s
#    networks:
#      database:
#        aliases:
#          - elasticsearch

secrets:
  POSTGRES_USER:
    file: ./env_vars/.POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./env_vars/.POSTGRES_PASSWORD
